name: Check

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, edited]

  push:
    branches:
      - main

jobs:
  Check:
    runs-on: windows-latest
    if: contains(github.event.pull_request.body, 'The workflow check was intentionally skipped.') == false
    steps:
      - uses: actions/checkout@master

      - name: Display repository name
        env:
          REPOSITORY: ${{ github.repository }}
        run: |
          Write-Host "The repository is: ${env:REPOSITORY}"

      - name: Install NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.202'

      - name: Install .NET 3 for the tools
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Install coveralls.net (to send test coverage)
        working-directory: src
        if: github.repository == 'aas-core-works/aas-package3-csharp9-dotnet5'
        run: dotnet tool install coveralls.net --version 2.0.0-beta0002

      - name: Instal dotnet tools
        working-directory: src
        run: dotnet tool restore

      - name: Check format
        working-directory: src
        run: powershell .\CheckFormat.ps1

      - name: Check bite-sized
        working-directory: src
        run: powershell .\CheckBiteSized.ps1

      - name: Check using directives
        working-directory: src
        run: powershell .\CheckUsings.ps1

      - name: Check for dead code
        working-directory: src
        run: powershell .\CheckDeadCode.ps1

      - name: Check TODOs
        working-directory: src
        run: powershell .\CheckTodos.ps1

      - name: Check doctests
        working-directory: src
        run: powershell .\Doctest.ps1 -check

      - name: Download samples
        working-directory: src
        run: powershell .\DownloadSamples.ps1

      - name: Run tests
        working-directory: src
        run: powershell .\Test.ps1

      - name: Send to Coveralls
        working-directory: src
        env:
          HEAD_REF: ${{ github.head_ref }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          # At the moment we only run coveralls on main.
          # However, we leave this legacy logic here in case we introduce
          # new branching policy or new coverage publishing rules.
          if (${env:GITHUB_REF}.StartsWith("refs/pull/"))
          {
            $branch = ${env:HEAD_REF} -Replace 'refs/heads/', ''
          }
          else
          {
            $branch = ${env:GITHUB_REF} -Replace 'refs/heads/', ''
          }

          $commit = $env:GITHUB_SHA

          echo "Branch is: $branch"
          echo "Commit is: $commit"

          dotnet tool run csmacnz.Coveralls --opencover -i AasCore.Aas3.Package.Tests\coverage.opencover.xml --useRelativePaths --repoToken $env:COVERALLS_REPO_TOKEN --commitId $commit --commitBranch $branch

      - name: Inspect code
        working-directory: src
        run: powershell .\InspectCode.ps1
