name: Check style

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, edited]

  push:
    branches:
      - main

jobs:
  Check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master

      - name: Display repository name
        env:
          REPOSITORY: ${{ github.repository }}
        run: |
          Write-Host "The repository is: ${env:REPOSITORY}"

      - name: Install NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.201'


      - name: Install dotnet tools
        working-directory: src
        run: dotnet tool restore

      - name: Check format
        working-directory: src
        run: powershell .\CheckFormat.ps1

      - name: Check bite-sized
        working-directory: src
        run: powershell .\CheckBiteSized.ps1

      - name: Check using directives
        working-directory: src
        run: powershell .\CheckUsings.ps1

      - name: Check for dead code
        working-directory: src
        run: powershell .\CheckDeadCode.ps1

      - name: Check TODOs
        working-directory: src
        run: powershell .\CheckTodos.ps1

      - name: Check doctests
        working-directory: src
        run: powershell .\Doctest.ps1 -check

      - name: Build for inspection
        working-directory: src
        run: dotnet build -c DebugSlow

      - name: Inspect code
        working-directory: src
        run: powershell .\InspectCode.ps1
